-- Sorgu 1:
SELECT 
    t.AD AS TAKIM_ADI,
    p.AD + ' ' + p.SOYAD AS FUTBOLCU_ADI_SOYADI,
    s.BASLANGIC_TARIHI,
    s.AYLIK_UCRET
FROM 
    SOZLESME s
    JOIN TAKIM t ON s.TAKIM_ID = t.TAKIM_ID
    JOIN PERSONEL p ON s.PERSONEL_ID = p.PERSONEL_ID
WHERE 
    p.POZISYON_ID = 1
    AND YEAR(s.BASLANGIC_TARIHI) = YEAR(GETDATE())
    AND s.AYLIK_UCRET = (
        SELECT TOP 1 s2.AYLIK_UCRET
        FROM SOZLESME s2
        JOIN PERSONEL p2 ON s2.PERSONEL_ID = p2.PERSONEL_ID
        WHERE 
            s2.TAKIM_ID = s.TAKIM_ID
            AND p2.POZISYON_ID = 1
            AND YEAR(s2.BASLANGIC_TARIHI) = YEAR(GETDATE())
        ORDER BY s2.AYLIK_UCRET DESC
    )
ORDER BY 
    s.AYLIK_UCRET DESC,
    t.AD;